# Generated by Django 3.2.7 on 2021-11-18 08:52

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('poster', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('regular_ticket', models.IntegerField()),
                ('vip_ticket', models.IntegerField()),
                ('max_attendance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('regular_tickets', models.IntegerField(blank=True, default=0, null=True)),
                ('vip_tickets', models.IntegerField(blank=True, default=0, null=True)),
                ('total_spend', models.IntegerField(default=0)),
                ('transacted_on', models.DateTimeField(auto_now_add=True)),
                ('transaction_code', models.CharField(max_length=12)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
            options={
                'ordering': ['-transacted_on'],
            },
        ),
    ]
